import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import dashboard from "@/components/Navbar"

const montserrat = Montserrat({ subsets: ["latin"] });
const mostrarNavbar = true;

export const metadata: Metadata = {
  title: "GeoTransit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} `}>
        {mostrarNavbar && <Navbar />}
        {children}
      </body>
    </html>
  );
}
